Made the service script more reliable

diff --git a/templates/wsl-keeagent.j2 b/templates/wsl-keeagent.j2
--- a/templates/wsl-keeagent.j2
+++ b/templates/wsl-keeagent.j2
@@ -15,24 +15,27 @@
 
 export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
 
-BASE={{ wsl_keeagent_service }}
-DAEMON_BIN={{ wsl_keeagent_script_path }}/msysgit2unix-socket.py
+BASE="{{ wsl_keeagent_service }}"
+DAEMON_SCRIPT="{{ wsl_keeagent_script_name }}"
 DAEMON_DESC="$BASE"
-DAEMON_PIDFILE=/var/run/msysgit2unix-socket.pid
+DAEMON_BIN="{{ wsl_keeagent_script_path }}/$DAEMON_SCRIPT"
+DAEMON_PIDFILE="/var/run/{{ (wsl_keeagent_script_name | splitext)[0] }}.pid"
 DAEMON_LOGFILE="/var/log/$BASE.log"
 DAEMON_OPTS="--timeout 3"
+MSYSGIT_PATH="{{ wsl_keeagent_msysgit_socket }}"
+SOCKET_PATH="{{ wsl_keeagent_ssh_agent_socket }}"
 
 # Get lsb functions
 source /lib/lsb/init-functions
 
 # Check wsl-keeagent is present
-if [ ! -x $DAEMON_BIN ]; then
+if [[ ! -x $DAEMON_BIN ]]; then
     log_failure_msg "$DAEMON_BIN not present or not executable"
     exit 1
 fi
 
 fail_unless_root() {
-    if [ "$(id -u)" != '0' ]; then
+    if [[ "$(id -u)" != '0' ]]; then
         log_failure_msg "$DAEMON_DESC must be run as root"
         exit 1
     fi
@@ -43,51 +46,87 @@ case "$1" in
         fail_unless_root
         log_begin_msg "Starting $DAEMON_DESC: $BASE"
 
+        # Discover pid from pidfile
+        daemon_pid="$(cat $DAEMON_PIDFILE 2>/dev/null)"
+        if [[ -n "$daemon_pid" || -f "$DAEMON_PIDFILE" || -S "$SOCKET_PATH" ]] ; then
+            if [[ -n "$daemon_pid" && -f "$DAEMON_PIDFILE" && -S "$SOCKET_PATH" ]] ; then
+                log_warning_msg "$BASE already running."
+                exit 0
+
+            else
+                log_warning_msg "$BASE is in an unclean status. Cannot start."
+                exit 1
+
+            fi
+        fi
+
         # Start the daemon
         $DAEMON_BIN \
             --pidfile $DAEMON_PIDFILE \
             $DAEMON_OPTS \
-            {{ wsl_keeagent_msysgit_socket }}:{{ wsl_keeagent_ssh_agent_socket }} \
+            "$MSYSGIT_PATH:$SOCKET_PATH" \
                 >> "$DAEMON_LOGFILE" 2>&1
-        result=$?
+        sleep 1
 
-        log_end_msg $result
-        exit $result
+        # Discover pid from pidfile
+        daemon_pid="$(cat $DAEMON_PIDFILE 2>/dev/null)"
+        if [[ -n "$daemon_pid" && -f "$DAEMON_PIDFILE" && -S "$SOCKET_PATH" ]] ; then
+            log_success_msg "$BASE is running"
+            exit 0
+        else
+            log_failure_msg "$BASE is NOT running"
+            exit 1
+        fi
         ;;
 
     stop)
         fail_unless_root
+        log_begin_msg "Stopping $DAEMON_DESC: $BASE"
 
-        if [ -f "$DAEMON_PIDFILE" ]; then
-            log_begin_msg "Stopping $DAEMON_DESC: $BASE"
+        if [[ -f "$DAEMON_PIDFILE" ]]; then
+            # Discover pid from pidfile
             daemon_pid="$(cat $DAEMON_PIDFILE 2>/dev/null)"
 
             # Stop the process
-            [ -n "$daemon_pid" ] && \
-                ps -p $daemon_pid > /dev/null 2>&1 && \
-                kill -SIGTERM $daemon_pid
-
-            if [ -n "$daemon_pid" ] ; then
-                # Test if still running
+            if [[ -n "$daemon_pid" ]] ; then
                 ps -p $daemon_pid > /dev/null 2>&1
-                result=$?
-                # Removing PID file
-                [ -f "$DAEMON_PIDFILE" ] && \
-                    rm "$DAEMON_PIDFILE" > /dev/null 2>&1
+                kill -SIGTERM $daemon_pid && sleep 1
             fi
 
-            log_end_msg $result
+            # Try to discover the PID via a different route
+            daemon_pid="$(pgrep -f $DAEMON_SCRIPT)"
+
+            if [[ -n "$process_pid" ]]; then
+                kill -SIGKILL $daemon_pid && sleep 1
+                rm "$DAEMON_PIDFILE" "$SOCKET_PATH" > /dev/null 2>&1
+            fi
+
+            log_success_msg "$BASE is stopped."
             exit $result
+
         else
-            log_warning_msg "$BASE already stopped - file $DAEMON_PIDFILE not found."
+            # Try to discover the PID via a different route
+            daemon_pid="$(pgrep -f $DAEMON_SCRIPT)"
+
+            if [[ -n "$daemon_pid" ]]; then
+                kill -SIGTERM $daemon_pid && sleep 1
+                log_success_msg "$BASE is stopped."
+
+            else
+                log_warning_msg "$BASE already stopped."
+
+            fi
         fi
+
+        # Sometimes there are leftovers
+        rm "$DAEMON_PIDFILE" "$SOCKET_PATH" > /dev/null 2>&1
         ;;
 
     restart)
         fail_unless_root
 
         daemon_pid="$(cat $DAEMON_PIDFILE 2>/dev/null)"
-        [ -n "$daemon_pid" ] && ps -p $daemon_pid > /dev/null 2>&1 && \
+            [[ -n "$daemon_pid" ]] && ps -p $daemon_pid > /dev/null 2>&1 && \
             $0 stop
 
         $0 start
@@ -97,8 +136,13 @@ case "$1" in
         status_of_proc -p "$DAEMON_PIDFILE" "$DAEMON_BIN" "$DAEMON_DESC"
         ;;
 
+    debug)
+        shift
+        /bin/bash -eux $0 $@
+        ;;
+
     *)
-        echo "Usage: service $BASE {start|stop|restart|status}"
+        echo "Usage: service $BASE {start|stop|restart|status|debug <action>}"
         exit 1
         ;;
 esac
